import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/commons/header/Header";
// import TopNotification from "@/components/header/TopNotification";
// import Navbar from "@/components/header/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
      <Header/>
      {/* we can also use like this  */}
      {/* <TopNotification/>
      <Navbar/> */}
        {children}
      </body>
    </html>
  );
}



